# Generated by Django 2.0.7 on 2018-09-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
