# Generated by Django 2.0.7 on 2018-09-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180912_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('publish', models.CharField(max_length=32)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
